# Generated by Django 2.2.9 on 2020-03-14 09:25

import django.core.validators
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('stars', django_mysql.models.ListCharField(models.CharField(max_length=35), max_length=5000, size=100)),
                ('writer', django_mysql.models.ListCharField(models.CharField(max_length=35), max_length=1000, size=20)),
                ('director', django_mysql.models.ListCharField(models.CharField(max_length=35), max_length=750, size=15)),
            ],
        ),
    ]
